CREATE DATABASE TRABSON;

ALTER DATABASE `trabson` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;


CREATE TABLE USUARIO(
    LOGIN VARCHAR(30),
    SENHA VARCHAR(50),
    PRIMARY KEY (LOGIN)

);

-- INSERT INTO USUARIO(LOGIN,SENHA) VALUES ('GOKU','12345');
-- INSERT INTO USUARIO(LOGIN,SENHA) VALUES ('VEGETA','12345');
/*Hash MD5*/
INSERT INTO USUARIO(LOGIN,SENHA) VALUES ('GOKU','827ccb0eea8a706c4c34a16891f84e7b');
INSERT INTO USUARIO(LOGIN,SENHA) VALUES ('VEGETA','827ccb0eea8a706c4c34a16891f84e7b');



CREATE TABLE CONTATO(
    ID_CONTATO INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100),
    EMAIL VARCHAR(50),
    MENSAGEM VARCHAR(1000),
    TIPO CHAR(1)

);

CREATE TABLE PACIENTE
(
    COD_PACIENTE INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100),
    TELEFONE VARCHAR(15)

);



INSERT INTO PACIENTE VALUES(1,'Vegeta','998432456');
INSERT INTO PACIENTE VALUES(2,'Gohan','8845621226');
INSERT INTO PACIENTE VALUES(3,'Piccolo','8446486489');

CREATE TABLE AGENDA
(
    COD_AGENDAMENTO INTEGER PRIMARY KEY AUTO_INCREMENT,
    DATA DATE,
    HORA INTEGER,
    COD_FUNCIONARIO INTEGER,
    COD_PACIENTE INTEGER,
    FOREIGN KEY (COD_FUNCIONARIO) REFERENCES FUNCIONARIO(COD_FUNCIONARIO),
    FOREIGN KEY (COD_PACIENTE) REFERENCES PACIENTE(COD_PACIENTE)

);

INSERT INTO AGENDA VALUES(1,'2017-10-30',8,24,1);

INSERT INTO AGENDA VALUES(2,'2017-11-16',9,26,2);
INSERT INTO AGENDA VALUES(3,'2017-11-16',9,24,3);




CREATE TABLE FUNCIONARIO
(
    COD_FUNCIONARIO INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME_FUNC VARCHAR(100),
    DT_NASC DATE,
    SEXO CHAR(1),
    EST_CIVIL CHAR(1),
    CARGO VARCHAR(15),
    ESP_MEDICA VARCHAR(50),
    CPF VARCHAR(15),
    RG VARCHAR(15),
    OUTRO VARCHAR(15)

);


INSERT INTO FUNCIONARIO VALUES (NULL,'JOSE DA SILVA','1990-10-11','m','c','medico','cadiologia','123','000',null)
INSERT INTO FUNCIONARIO VALUES (NULL,'Adriana','1990-10-12','f','s','enferemeiro',null,'000','001',null)
INSERT INTO FUNCIONARIO VALUES (NULL,'Rafael','1990-11-12','m','d','secretario',null,'002','002',null)




CREATE TABLE ENDERECO
(
    CEP VARCHAR(15),
    TIPO_LOG VARCHAR(8),
    LOGRADOURO VARCHAR(50),
    NUM INTEGER,
    COMP VARCHAR(50),
    BAIRRO VARCHAR(30),
    CIDADE VARCHAR(30),
    ESTADO VARCHAR(3),
    COD_FUNCIONARIO INTEGER,
    PRIMARY KEY (CEP,NUM),
    FOREIGN KEY (COD_FUNCIONARIO) REFERENCES FUNCIONARIO(COD_FUNCIONARIO)

);


INSERT INTO ENDERECO VALUES ('38412294','RUA','DO GARCOM',165,NULL,'JARDIM DAS PALMEIRAS','UBERLANDIA','MG',NULL)
INSERT INTO ENDERECO VALUES ('38412294','RUA','DO GARCOM',172,NULL,'JARDIM DAS PALMEIRAS','UBERLANDIA','MG',NULL)
INSERT INTO ENDERECO VALUES ('123','RUA','DO GARCOM',172,NULL,'JARDIM DAS PALMEIRAS','UBERLANDIA','MG',24);
INSERT INTO ENDERECO VALUES ('111','RUA','ALGUMA RUA ALEATORIA',172,NULL,'ALGUM BAIRRO DESSE PLANETA','ALGUMA CIDADE DESSE PLANETA','MG',25);
INSERT INTO ENDERECO VALUES ('13','RUA','GIDEÃO',172,NULL,'ALGUM DESSE BRASILZÃO','UBERLÂNDIA','MG',26);
