CREATE DATABASE TRABSON;

CREATE TABLE USUARIO(
    LOGIN VARCHAR(30),
    SENHA VARCHAR(50),
    PRIMARY KEY (LOGIN)

);

INSERT INTO USUARIO(LOGIN,SENHA) VALUES ('GOKU','12345');
INSERT INTO USUARIO(LOGIN,SENHA) VALUES ('VEGETA','12345');



CREATE TABLE CONTATO(
    ID_CONTATO INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100),
    EMAIL VARCHAR(50),
    MENSAGEM VARCHAR(1000),
    TIPO CHAR(1)

);

CREATE TABLE PACIENTE
(
    COD_PACIENTE INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100),
    TELEFONE VARCHAR(15)

);




CREATE TABLE FUNCIONARIO
(
    COD_FUNCIONARIO INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME_FUNC VARCHAR(100),
    DT_NASC DATE,
    SEXO CHAR(1),
    EST_CIVIL CHAR(1),
    CARGO VARCHAR(15),
    ESP_MEDICA VARCHAR(50),
    CPF VARCHAR(15),
    RG VARCHAR(15),
    OUTRO VARCHAR(15)

);

CREATE TABLE ENDERECO
(
    CEP VARCHAR(15),
    TIPO_LOG VARCHAR(8),
    LOGRADOURO VARCHAR(50),
    NUM INTEGER,
    COMP VARCHAR(50),
    BAIRRO VARCHAR(30),
    CIDADE VARCHAR(30),
    ESTADO VARCHAR(3),
    COD_FUNCIONARIO INTEGER,
    PRIMARY KEY (CEP,NUM),
    FOREIGN KEY (COD_FUNCIONARIO) REFERENCES FUNCIONARIO(COD_FUNCIONARIO)

);


INSERT INTO ENDERECO VALUES ('38412294','RUA','DO GARCOM',165,NULL,'JARDIM DAS PALMEIRAS','UBERLANDIA','MG',NULL)
INSERT INTO ENDERECO VALUES ('38412294','RUA','DO GARCOM',172,NULL,'JARDIM DAS PALMEIRAS','UBERLANDIA','MG',NULL)
INSERT INTO ENDERECO VALUES ('123','RUA','DO GARCOM',172,NULL,'JARDIM DAS PALMEIRAS','UBERLANDIA','MG',NULL)
INSERT INTO ENDERECO VALUES ('111','RUA','ALGUMA RUA ALEATORIA',172,NULL,'ALGUM BAIRRO DESSE PLANETA','ALGUMA CIDADE DESSE PLANETA','MG',NULL)
INSERT INTO ENDERECO VALUES ('123','RUA','GIDEÃO',172,NULL,'ALGUM DESSE BRASILZÃO','UBERLÂNDIA','MG',NULL)
